# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.7"

services:
  db:
    image: postgres:13-alpine
    container_name: listmonk_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: listmonk
      POSTGRES_USER: listmonk
      POSTGRES_DB: listmonk
    volumes:
      - listmonk-db-data:/var/lib/postgresql/data

  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      TZ: Etc/UTC
    depends_on:
      - db
    volumes:
      - ./listmonk-config:/listmonk/config
      # Adjust the path to your Listmonk configuration file

networks:
  listmonk_network:
    driver: bridge

volumes:
  listmonk-db-data:


